set test "Completion via comp_load() should be installed"
set cmd "complete -p a2ps"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load a2ps\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/a2ps.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p a2ps"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt a2ps\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/a2ps.exp"
