set test "Completion via comp_load() should be installed"
set cmd "complete -p animate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load animate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/animate.exp"


set test "Completion via _animate() should be installed"
set cmd "complete -p animate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _animate animate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/animate.exp"
