set test "Completion via comp_load() should be installed"
set cmd "complete -p bash"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load bash\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/bash.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p bash"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt bash\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/bash.exp"
