set test "Completion via comp_load() should be installed"
set cmd "complete -p btdownloadcurses.py"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load btdownloadcurses.py\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/btdownloadcurses.py.exp"


set test "Completion via _btdownload() should be installed"
set cmd "complete -p btdownloadcurses.py"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _btdownload btdownloadcurses.py\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/btdownloadcurses.py.exp"
