set test "Completion via comp_load() should be installed"
set cmd "complete -p dpkg-reconfigure"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load dpkg-reconfigure\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dpkg-reconfigure.exp"


set test "Completion via _dpkg-reconfigure() should be installed"
set cmd "complete -p dpkg-reconfigure"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _dpkg-reconfigure dpkg-reconfigure\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dpkg-reconfigure.exp"
