set test "Completion via comp_load() should be installed"
set cmd "complete -p ifup"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load ifup\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ifup.exp"


set test "Completion via _ifupdown() should be installed"
set cmd "complete -p ifup"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _ifupdown ifup\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ifup.exp"
