set test "Completion via comp_load() should be installed"
set cmd "complete -p objcopy"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load objcopy\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/objcopy.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p objcopy"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt objcopy\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/objcopy.exp"
