set test "Completion via comp_load() should be installed"
set cmd "complete -p patch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load patch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/patch.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p patch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt patch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/patch.exp"
