set test "Completion via comp_load() should be installed"
set cmd "complete -p svk"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load svk\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svk.exp"


set test "Completion via _svk() should be installed"
set cmd "complete -p svk"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _svk svk\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svk.exp"
