set test "Completion via comp_load() should be installed"
set cmd "complete -p svnlook"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load svnlook\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svnlook.exp"


set test "Completion via _svnlook() should be installed"
set cmd "complete -p svnlook"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _svnlook svnlook\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svnlook.exp"
