set test "Completion via comp_load() should be installed"
set cmd "complete -p unset"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load unset\r\n/@" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/unset.exp"


set test "Completion via -v should be installed"
set cmd "complete -p unset"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -v unset\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/unset.exp"
