set test "Completion via comp_load() should be installed"
set cmd "complete -p vgmknodes"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load vgmknodes\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgmknodes.exp"


set test "Completion via _vgmknodes() should be installed"
set cmd "complete -p vgmknodes"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _vgmknodes vgmknodes\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgmknodes.exp"
