set test "Completion via comp_load() should be installed"
set cmd "complete -p withlist"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load withlist\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/withlist.exp"


set test "Completion via _withlist() should be installed"
set cmd "complete -p withlist"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _withlist withlist\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/withlist.exp"
