#!/bin/bash

# NOTE: Specifying `--host' and `--target' allow one-time setup of
#       bash_completion_lib when runtest initializes.  E.g.:
#
#          $ runtest alias.exp cd.exp
#            * setup bash_completion_lib
#              o test alias.exp
#              o test cd.exp
#      
#       compared to:
#
#          $ runtest alias.exp cd.exp
#            * setup bash_completion_lib
#              o test alias.exp
#            * setup bash_completion_lib
#              o test cd.exp
#
#       I tried setting up bash_completion_lib within ./lib files, but DejaGnu
#       isn't initialized at that point (i.e. output of `expect' is shown on
#       stdout - `open_logs' hasn't run yet?).  And running code from a library
#       file isn't probably a good idea either.
runtest --outdir=log --tool=completionLib $* 
