set test "Completion via comp_load() should be installed"
set cmd "complete -p configure"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load configure\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/configure.exp"


set test "Completion via _configure_func() should be installed"
set cmd "complete -p configure"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _configure_func configure\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/configure.exp"
