set test "Completion via comp_load() should be installed"
set cmd "complete -p fmt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load fmt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/fmt.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p fmt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt fmt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/fmt.exp"
