set test "Completion via comp_load() should be installed"
set cmd "complete -p gcj"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gcj\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gcj.exp"


set test "Completion via _gcc() should be installed"
set cmd "complete -p gcj"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _gcc gcj\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gcj.exp"
