set test "Completion via comp_load() should be installed"
set cmd "complete -p gmplayer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gmplayer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gmplayer.exp"


set test "Completion via _mplayer() should be installed"
set cmd "complete -p gmplayer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _mplayer gmplayer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gmplayer.exp"
