set test "Completion via comp_load() should be installed"
set cmd "complete -p hg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load hg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/hg.exp"


set test "Completion via _hg() should be installed"
set cmd "complete -p hg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _hg hg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/hg.exp"
