set test "Completion via comp_load() should be installed"
set cmd "complete -p isql"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load isql\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/isql.exp"


set test "Completion via _isql() should be installed"
set cmd "complete -p isql"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _isql isql\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/isql.exp"
