set test "Completion via comp_load() should be installed"
set cmd "complete -p kplayer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load kplayer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/kplayer.exp"


set test "Completion via _mplayer() should be installed"
set cmd "complete -p kplayer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _mplayer kplayer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/kplayer.exp"
