set test "Completion via comp_load() should be installed"
set cmd "complete -p look"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load look\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/look.exp"


set test "Completion via _look() should be installed"
set cmd "complete -p look"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _look look\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/look.exp"
