set test "Completion via comp_load() should be installed"
set cmd "complete -p lvreduce"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load lvreduce\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvreduce.exp"


set test "Completion via _lvreduce() should be installed"
set cmd "complete -p lvreduce"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _lvreduce lvreduce\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvreduce.exp"
