set test "Completion via comp_load() should be installed"
set cmd "complete -p mencoder"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mencoder\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mencoder.exp"


set test "Completion via _mplayer() should be installed"
set cmd "complete -p mencoder"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _mplayer mencoder\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mencoder.exp"
