set test "Completion via comp_load() should be installed"
set cmd "complete -p mtx"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load mtx\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mtx.exp"


set test "Completion via _mtx() should be installed"
set cmd "complete -p mtx"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _mtx mtx\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mtx.exp"
