set test "Completion via comp_load() should be installed"
set cmd "complete -p mutt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -o filenames -F comp_load mutt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mutt.exp"


set test "Completion via _mutt() should be installed"
set cmd "complete -p mutt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -o filenames -F _mutt mutt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mutt.exp"
