set test "Completion via comp_load() should be installed"
set cmd "complete -p pvs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load pvs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvs.exp"


set test "Completion via _pvs() should be installed"
set cmd "complete -p pvs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _pvs pvs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvs.exp"
