set test "Completion via comp_load() should be installed"
set cmd "complete -p python"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load python\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/python.exp"


set test "Completion via _python() should be installed"
set cmd "complete -p python"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _python python\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/python.exp"
