set test "Completion via comp_load() should be installed"
set cmd "complete -p strip"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load strip\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/strip.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p strip"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt strip\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/strip.exp"
