set test "Completion via comp_load() should be installed"
set cmd "complete -p sysctl"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load sysctl\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sysctl.exp"


set test "Completion via _sysctl() should be installed"
set cmd "complete -p sysctl"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _sysctl sysctl\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sysctl.exp"
