set test "Completion via comp_load() should be installed"
set cmd "complete -p uname"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load uname\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/uname.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p uname"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _longopt uname\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/uname.exp"
