set test "Completion via comp_load() should be installed"
set cmd "complete -p chkconfig"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load chkconfig\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/chkconfig.exp"


set test "Completion via _chkconfig() should be installed"
set cmd "complete -p chkconfig"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _chkconfig chkconfig\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/chkconfig.exp"
