set test "Completion via comp_load() should be installed"
set cmd "complete -p co"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load co\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/co.exp"


set test "Completion via _rcs() should be installed"
set cmd "complete -p co"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _rcs co\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/co.exp"
