set test "Completion via comp_load() should be installed"
set cmd "complete -p cpio"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load cpio\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cpio.exp"


set test "Completion via _cpio() should be installed"
set cmd "complete -p cpio"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _cpio cpio\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cpio.exp"
