set test "Completion via comp_load() should be installed"
set cmd "complete -p dcop"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load dcop\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dcop.exp"


set test "Completion via _dcop() should be installed"
set cmd "complete -p dcop"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _dcop dcop\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dcop.exp"
