set test "Completion via comp_load() should be installed"
set cmd "complete -p df"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load df\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/df.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p df"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt df\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/df.exp"
