set test "Completion via comp_load() should be installed"
set cmd "complete -p find"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load find\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/find.exp"


set test "Completion via _find() should be installed"
set cmd "complete -p find"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _find find\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/find.exp"
