set test "Completion via comp_load() should be installed"
set cmd "complete -p gpc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gpc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gpc.exp"


set test "Completion via _gcc() should be installed"
set cmd "complete -p gpc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _gcc gpc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gpc.exp"
