set test "Completion via comp_load() should be installed"
set cmd "complete -p gpg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load gpg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gpg.exp"


set test "Completion via _gpg() should be installed"
set cmd "complete -p gpg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _gpg gpg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gpg.exp"
