set test "Completion via comp_load() should be installed"
set cmd "complete -p irb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load irb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/irb.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p irb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt irb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/irb.exp"
