set test "Completion via comp_load() should be installed"
set cmd "complete -p killall"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load killall\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/killall.exp"


set test "Completion via _killall() should be installed"
set cmd "complete -p killall"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _killall killall\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/killall.exp"
