set test "Completion via comp_load() should be installed"
set cmd "complete -p kldunload"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load kldunload\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/kldunload.exp"


set test "Completion via _kldunload() should be installed"
set cmd "complete -p kldunload"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _kldunload kldunload\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/kldunload.exp"
