set test "Completion via comp_load() should be installed"
set cmd "complete -p ld"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load ld\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ld.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p ld"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt ld\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ld.exp"
