set test "Completion via comp_load() should be installed"
set cmd "complete -p lftp"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load lftp\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lftp.exp"


set test "Completion via _lftp() should be installed"
set cmd "complete -p lftp"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _lftp lftp\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lftp.exp"
