set test "Completion via comp_load() should be installed"
set cmd "complete -p ln"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load ln\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ln.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p ln"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt ln\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ln.exp"
