set test "Completion via comp_load() should be installed"
set cmd "complete -p openssl"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load openssl\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/openssl.exp"


set test "Completion via _openssl() should be installed"
set cmd "complete -p openssl"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _openssl openssl\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/openssl.exp"
