set test "Completion via comp_load() should be installed"
set cmd "complete -p portinstall"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o dirnames -F comp_load portinstall\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/portinstall.exp"


set test "Completion via _portinstall() should be installed"
set cmd "complete -p portinstall"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o dirnames -F _portinstall portinstall\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/portinstall.exp"
