set test "Completion via comp_load() should be installed"
set cmd "complete -p ptx"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load ptx\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ptx.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p ptx"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt ptx\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ptx.exp"
