set test "Completion via comp_load() should be installed"
set cmd "complete -p pvcreate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load pvcreate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvcreate.exp"


set test "Completion via _pvcreate() should be installed"
set cmd "complete -p pvcreate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _pvcreate pvcreate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvcreate.exp"
