set test "Completion via comp_load() should be installed"
set cmd "complete -p tightvncviewer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load tightvncviewer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tightvncviewer.exp"


set test "Completion via _tightvncviewer() should be installed"
set cmd "complete -p tightvncviewer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _tightvncviewer tightvncviewer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tightvncviewer.exp"
