set test "Completion via comp_load() should be installed"
set cmd "complete -p vgrename"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load vgrename\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgrename.exp"


set test "Completion via _vgrename() should be installed"
set cmd "complete -p vgrename"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _vgrename vgrename\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgrename.exp"
