set test "Completion via comp_load() should be installed"
set cmd "complete -p wget"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load wget\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/wget.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p wget"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _longopt wget\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/wget.exp"
