set test "Completion via comp_load() should be installed"
set cmd "complete -p who"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load who\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/who.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p who"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt who\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/who.exp"
