proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "readonly BASH_ARG"
send "$cmd\t"
expect {
    -re "^$cmd\r\nBASH_ARGC +BASH_ARGV +\r\n/@$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect

# Interrupt command by sending ^C

sleep 0.1; 
send \003;  # Control-c
expect -ex /@


teardown
