set test "Completion via comp_load() should be installed"
set cmd "complete -p cat"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load cat\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cat.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p cat"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt cat\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cat.exp"
