set test "Completion via comp_load() should be installed"
set cmd "complete -p dropdb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load dropdb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dropdb.exp"


set test "Completion via _dropdb() should be installed"
set cmd "complete -p dropdb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _dropdb dropdb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dropdb.exp"
