set test "Completion via comp_load() should be installed"
set cmd "complete -p larch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load larch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/larch.exp"


set test "Completion via _larch() should be installed"
set cmd "complete -p larch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _larch larch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/larch.exp"
