set test "Completion via comp_load() should be installed"
set cmd "complete -p lvchange"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load lvchange\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvchange.exp"


set test "Completion via _lvchange() should be installed"
set cmd "complete -p lvchange"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _lvchange lvchange\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvchange.exp"
