set test "Completion via comp_load() should be installed"
set cmd "complete -p module"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load module\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/module.exp"


set test "Completion via _module() should be installed"
set cmd "complete -p module"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _module module\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/module.exp"
