set test "Completion via comp_load() should be installed"
set cmd "complete -p pine"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load pine\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pine.exp"


set test "Completion via _pineaddr() should be installed"
set cmd "complete -p pine"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _pineaddr pine\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pine.exp"
