set test "Completion via comp_load() should be installed"
set cmd "complete -p ri"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load ri\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ri.exp"


set test "Completion via _ri() should be installed"
set cmd "complete -p ri"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _ri ri\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ri.exp"
