set test "Completion via comp_load() should be installed"
set cmd "complete -p sha1sum"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load sha1sum\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sha1sum.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p sha1sum"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt sha1sum\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sha1sum.exp"
