set test "Completion via comp_load() should be installed"
set cmd "complete -p shar"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load shar\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/shar.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p shar"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt shar\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/shar.exp"
