set test "Completion via comp_load() should be installed"
set cmd "complete -p uniq"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load uniq\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/uniq.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p uniq"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt uniq\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/uniq.exp"
