set test "Completion via comp_load() should be installed"
set cmd "complete -p aptitude"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load aptitude\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/aptitude.exp"


set test "Completion via aptitude() should be installed"
set cmd "complete -p aptitude"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F aptitude aptitude\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/aptitude.exp"
