set test "Completion via comp_load() should be installed"
set cmd "complete -p bison"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load bison\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/bison.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p bison"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt bison\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/bison.exp"
