set test "Completion via comp_load() should be installed"
set cmd "complete -p btdownloadheadless.py"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load btdownloadheadless.py\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/btdownloadheadless.py.exp"


set test "Completion via _btdownload() should be installed"
set cmd "complete -p btdownloadheadless.py"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _btdownload btdownloadheadless.py\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/btdownloadheadless.py.exp"
