set test "Completion via comp_load() should be installed"
set cmd "complete -p createdb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load createdb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/createdb.exp"


set test "Completion via _createdb() should be installed"
set cmd "complete -p createdb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _createdb createdb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/createdb.exp"
