set test "Completion via comp_load() should be installed"
set cmd "complete -p gcc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gcc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gcc.exp"


set test "Completion via _gcc() should be installed"
set cmd "complete -p gcc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _gcc gcc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gcc.exp"
