set test "Completion via comp_load() should be installed"
set cmd "complete -p insmod"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load insmod\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/insmod.exp"


set test "Completion via _insmod() should be installed"
set cmd "complete -p insmod"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _insmod insmod\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/insmod.exp"
