set test "Completion via comp_load() should be installed"
set cmd "complete -p iwpriv"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load iwpriv\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/iwpriv.exp"


set test "Completion via _iwpriv() should be installed"
set cmd "complete -p iwpriv"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _iwpriv iwpriv\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/iwpriv.exp"
