set test "Completion via comp_load() should be installed"
set cmd "complete -p kill"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load kill\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/kill.exp"


set test "Completion via _kill() should be installed"
set cmd "complete -p kill"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _kill kill\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/kill.exp"
