set test "Completion via comp_load() should be installed"
set cmd "complete -p mmsitepass"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load mmsitepass\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mmsitepass.exp"


set test "Completion via _mmsitepass() should be installed"
set cmd "complete -p mmsitepass"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _mmsitepass mmsitepass\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mmsitepass.exp"
