set test "Completion via comp_load() should be installed"
set cmd "complete -p rdict"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load rdict\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rdict.exp"


set test "Completion via _dict() should be installed"
set cmd "complete -p rdict"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _dict rdict\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rdict.exp"
