set test "Completion via comp_load() should be installed"
set cmd "complete -p svn"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load svn\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svn.exp"


set test "Completion via _svn() should be installed"
set cmd "complete -p svn"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _svn svn\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svn.exp"
