set test "Completion via comp_load() should be installed"
set cmd "complete -p touch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load touch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/touch.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p touch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt touch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/touch.exp"
