    # Use emacs key bindings
set -o emacs
    # Use bash strict mode
set -o posix
    # Unset `command_not_found_handle' as defined on Debian/Ubuntu, because this handling
    # troubles and slows down testing?
unset -f command_not_found_handle
	# Set prompt to ignore current working directory; display path starting from here
	# E.g. prompt: //fixture1/1-1@
mwd=$(pwd)
export PS1='$(cwd=$(pwd); echo ${cwd#$mwd}/)@'
	# Configure readline
export INPUTRC=$(pwd)/config/inputrc
	# Ensure enough columns so expect doesn't have to care about line breaks
stty columns 150
    # Disable cache
COMP_CACHE=
