set test "Completion via comp_load() should be installed"
set cmd "complete -p g77"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load g77\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/g77.exp"


set test "Completion via _gcc() should be installed"
set cmd "complete -p g77"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _gcc g77\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/g77.exp"
