set test "Completion via comp_load() should be installed"
set cmd "complete -p java"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load java\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/java.exp"


set test "Completion via _java() should be installed"
set cmd "complete -p java"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _java java\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/java.exp"
