set test "Completion via comp_load() should be installed"
set cmd "complete -p ls"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load ls\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ls.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p ls"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt ls\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ls.exp"
