set test "Completion via comp_load() should be installed"
set cmd "complete -p paste"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load paste\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/paste.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p paste"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt paste\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/paste.exp"
