set test "Completion via comp_load() should be installed"
set cmd "complete -p arch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load arch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/arch.exp"


set test "Completion via _arch() should be installed"
set cmd "complete -p arch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _arch arch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/arch.exp"
