set test "Completion via comp_load() should be installed"
set cmd "complete -p composite"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load composite\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/composite.exp"


set test "Completion via _composite() should be installed"
set cmd "complete -p composite"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _composite composite\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/composite.exp"
