set test "Completion via comp_load() should be installed"
set cmd "complete -p cvs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load cvs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cvs.exp"


set test "Completion via _cvs() should be installed"
set cmd "complete -p cvs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _cvs cvs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cvs.exp"
