set test "Completion via comp_load() should be installed"
set cmd "complete -p enscript"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load enscript\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/enscript.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p enscript"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt enscript\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/enscript.exp"
