set test "Completion via comp_load() should be installed"
set cmd "complete -p expand"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load expand\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/expand.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p expand"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt expand\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/expand.exp"
