set test "Completion via comp_load() should be installed"
set cmd "complete -p links"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load links\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/links.exp"


set test "Completion via _links() should be installed"
set cmd "complete -p links"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _links links\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/links.exp"
