set test "Completion via comp_load() should be installed"
set cmd "complete -p objdump"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load objdump\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/objdump.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p objdump"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt objdump\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/objdump.exp"
