set test "Completion via comp_load() should be installed"
set cmd "complete -p sshmitm"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load sshmitm\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sshmitm.exp"


set test "Completion via _sshmitm() should be installed"
set cmd "complete -p sshmitm"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _sshmitm sshmitm\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sshmitm.exp"
