set test "Completion via comp_load() should be installed"
set cmd "complete -p sshow"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load sshow\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sshow.exp"


set test "Completion via _sshow() should be installed"
set cmd "complete -p sshow"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _sshow sshow\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sshow.exp"
