set test "Completion via comp_load() should be installed"
set cmd "complete -p tac"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load tac\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tac.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p tac"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt tac\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tac.exp"
