set test "Completion via comp_load() should be installed"
set cmd "complete -p unrar"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load unrar\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/unrar.exp"


set test "Completion via _unrar() should be installed"
set cmd "complete -p unrar"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _unrar unrar\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/unrar.exp"
