set test "Completion via comp_load() should be installed"
set cmd "complete -p urlsnarf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load urlsnarf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/urlsnarf.exp"


set test "Completion via _urlsnarf() should be installed"
set cmd "complete -p urlsnarf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _urlsnarf urlsnarf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/urlsnarf.exp"
