set test "Completion via comp_load() should be installed"
set cmd "complete -p apt-get"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load apt-get\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/apt-get.exp"


set test "Completion via _apt_get() should be installed"
set cmd "complete -p apt-get"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _apt_get apt-get\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/apt-get.exp"
