set test "Completion via comp_load() should be installed"
set cmd "complete -p c++"
send "$cmd\r"
expect {
    -re "^complete -p c\\+\\+\r\ncomplete -o filenames -F comp_load c\\+\\+\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/c++.exp"


set test "Completion via _gcc() should be installed"
set cmd "complete -p c++"
send "$cmd\r"
expect {
    -re "^complete -p c\\+\\+\r\ncomplete -o filenames -F _gcc c\\+\\+\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/c++.exp"
