set test "Completion via comp_load() should be installed"
set cmd "complete -p ci"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load ci\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ci.exp"


set test "Completion via _rcs() should be installed"
set cmd "complete -p ci"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _rcs ci\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ci.exp"
