set test "Completion via comp_load() should be installed"
set cmd "complete -p iconv"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load iconv\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/iconv.exp"


set test "Completion via _iconv() should be installed"
set cmd "complete -p iconv"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _iconv iconv\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/iconv.exp"
