set test "Completion via comp_load() should be installed"
set cmd "complete -p less"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load less\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/less.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p less"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt less\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/less.exp"
