set test "Completion via comp_load() should be installed"
set cmd "complete -p man"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load man\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/man.exp"


set test "Completion via _man() should be installed"
set cmd "complete -p man"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _man man\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/man.exp"
