set test "Completion via comp_load() should be installed"
set cmd "complete -p muttng"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -o filenames -F comp_load muttng\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/muttng.exp"


set test "Completion via _mutt() should be installed"
set cmd "complete -p muttng"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -o filenames -F _mutt muttng\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/muttng.exp"
