set test "Completion via comp_load() should be installed"
set cmd "complete -p mv"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mv\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mv.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p mv"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt mv\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mv.exp"
