set test "Completion via comp_load() should be installed"
set cmd "complete -p od"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load od\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/od.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p od"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt od\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/od.exp"
