set test "Completion via comp_load() should be installed"
set cmd "complete -p p4"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load p4\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/p4.exp"


set test "Completion via _p4() should be installed"
set cmd "complete -p p4"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _p4 p4\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/p4.exp"
