set test "Completion via comp_load() should be installed"
set cmd "complete -p povray"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load povray\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/povray.exp"


set test "Completion via _povray() should be installed"
set cmd "complete -p povray"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _povray povray\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/povray.exp"
