set test "Completion via comp_load() should be installed"
set cmd "complete -p rsync"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -o nospace -F comp_load rsync\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rsync.exp"


set test "Completion via _rsync() should be installed"
set cmd "complete -p rsync"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -o nospace -F _rsync rsync\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rsync.exp"
