set test "Completion via comp_load() should be installed"
set cmd "complete -p spovray"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load spovray\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/spovray.exp"


set test "Completion via _povray() should be installed"
set cmd "complete -p spovray"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _povray spovray\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/spovray.exp"
