set test "Completion via comp_load() should be installed"
set cmd "complete -p vncviewer"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load vncviewer\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


switch -glob [realcommand vncviewer] {
    ""              {set fname ""}
    *xvnc4viewer    {set fname xvnc4viewer}
    *tightvncviewer -
    default         {set fname tightvncviewer}
}; # switch


if [string length $fname] {
    source "lib/completions/$fname.exp"


    set test "Completion via other function than comp_load() should be installed"
    set cmd "complete -p vncviewer"
    send "$cmd\r"
    expect {
	-re "^$cmd\r\ncomplete -F _$fname vncviewer\r\n/@$" { pass "$test" }
	-re /@ { fail "$test at prompt" }
    }; # expect


    source "lib/completions/$fname.exp"
}; # if
