proc setup {} {
    set cmd "unalias -a";  # Remove all aliases
    send "$cmd\r"
    expect -ex "$cmd\r\n/@"
    set cmd "alias foo=bar"
    send "$cmd\r"
    expect -ex "$cmd\r\n/@"
    set cmd "alias bar='foo foo'"
    send "$cmd\r"
    expect -ex "$cmd\r\n/@"
}; # setup()


proc teardown {} {
    set cmd "unalias -a";  # Remove all aliases
    send "$cmd\r"
    expect -ex "$cmd\r\n/@"
}; # teardown()


setup


set test "Tab should complete alias"
    # Try completion
set cmd "alias "
send "$cmd\t"
set expected "^$cmd\r\nbar= +foo= +\r\n/@$cmd$"
expect {
    -re $expected  { pass "$test" }
    -re /@ { fail "$test at prompt" }
    default { fail "$test" }
}; # expect


# Interrupt command by sending ^C

sleep 0.1; 
send \003;  # Control-c
expect -ex /@


teardown
