set test "Completion via comp_load() should be installed"
set cmd "complete -p cleanarch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load cleanarch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cleanarch.exp"


set test "Completion via _cleanarch() should be installed"
set cmd "complete -p cleanarch"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _cleanarch cleanarch\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cleanarch.exp"
