set test "Completion via comp_load() should be installed"
set cmd "complete -p csplit"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load csplit\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/csplit.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p csplit"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt csplit\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/csplit.exp"
