set test "Completion via comp_load() should be installed"
set cmd "complete -p cut"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load cut\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cut.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p cut"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt cut\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/cut.exp"
