set test "Completion via comp_load() should be installed"
set cmd "complete -p getent"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load getent\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/getent.exp"


set test "Completion via _getent() should be installed"
set cmd "complete -p getent"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _getent getent\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/getent.exp"
