set test "Completion via comp_load() should be installed"
set cmd "complete -p identify"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load identify\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/identify.exp"


set test "Completion via _identify() should be installed"
set cmd "complete -p identify"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _identify identify\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/identify.exp"
