set test "Completion via comp_load() should be installed"
set cmd "complete -p lvdisplay"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load lvdisplay\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvdisplay.exp"


set test "Completion via _lvdisplay() should be installed"
set cmd "complete -p lvdisplay"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _lvdisplay lvdisplay\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvdisplay.exp"
