set test "Completion via comp_load() should be installed"
set cmd "complete -p rcsdiff"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load rcsdiff\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rcsdiff.exp"


set test "Completion via _rcs() should be installed"
set cmd "complete -p rcsdiff"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _rcs rcsdiff\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rcsdiff.exp"
