set test "Completion via comp_load() should be installed"
set cmd "complete -p rmdir"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load rmdir\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rmdir.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p rmdir"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt rmdir\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rmdir.exp"
