set test "Completion via comp_load() should be installed"
set cmd "complete -p snownews"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load snownews\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/snownews.exp"


set test "Completion via _snownews() should be installed"
set cmd "complete -p snownews"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _snownews snownews\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/snownews.exp"
