set test "Completion via comp_load() should be installed"
set cmd "complete -p tail"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load tail\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tail.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p tail"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt tail\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tail.exp"
