set test "Completion via comp_load() should be installed"
set cmd "complete -p aspell"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load aspell\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/aspell.exp"


set test "Completion via _aspell() should be installed"
set cmd "complete -p aspell"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _aspell aspell\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/aspell.exp"
