set test "Completion via comp_load() should be installed"
set cmd "complete -p autoconf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load autoconf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/autoconf.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p autoconf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt autoconf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/autoconf.exp"
