set test "Completion via comp_load() should be installed"
set cmd "complete -p dsniff"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load dsniff\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dsniff.exp"


set test "Completion via _dsniff() should be installed"
set cmd "complete -p dsniff"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _dsniff dsniff\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dsniff.exp"
