set test "Completion via comp_load() should be installed"
set cmd "complete -p gdb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gdb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gdb.exp"


set test "Completion via _gdb() should be installed"
set cmd "complete -p gdb"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _gdb gdb\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gdb.exp"
