set test "Completion via comp_load() should be installed"
set cmd "complete -p head"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load head\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/head.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p head"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt head\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/head.exp"
