set test "Completion via comp_load() should be installed"
set cmd "complete -p javadoc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load javadoc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/javadoc.exp"


set test "Completion via _javadoc() should be installed"
set cmd "complete -p javadoc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _javadoc javadoc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/javadoc.exp"
