set test "Completion via comp_load() should be installed"
set cmd "complete -p macof"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load macof\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/macof.exp"


set test "Completion via _macof() should be installed"
set cmd "complete -p macof"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _macof macof\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/macof.exp"
