set test "Completion via comp_load() should be installed"
set cmd "complete -p mknod"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mknod\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mknod.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p mknod"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt mknod\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mknod.exp"
