set test "Completion via comp_load() should be installed"
set cmd "complete -p pvchange"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load pvchange\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvchange.exp"


set test "Completion via _pvchange() should be installed"
set cmd "complete -p pvchange"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _pvchange pvchange\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvchange.exp"
