set test "Completion via comp_load() should be installed"
set cmd "complete -p sbcl-mt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load sbcl-mt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sbcl-mt.exp"


set test "Completion via _sbcl() should be installed"
set cmd "complete -p sbcl-mt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _sbcl sbcl-mt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sbcl-mt.exp"
