set test "Completion via comp_load() should be installed"
set cmd "complete -p sort"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load sort\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sort.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p sort"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt sort\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/sort.exp"
