set test "Completion via comp_load() should be installed"
set cmd "complete -p vgremove"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load vgremove\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgremove.exp"


set test "Completion via _vgremove() should be installed"
set cmd "complete -p vgremove"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _vgremove vgremove\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgremove.exp"
