set test "Completion via comp_load() should be installed"
set cmd "complete -p wc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load wc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/wc.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p wc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt wc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/wc.exp"
