set test "Completion via comp_load() should be installed"
set cmd "complete -p dselect"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load dselect\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dselect.exp"


set test "Completion via _dselect() should be installed"
set cmd "complete -p dselect"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _dselect dselect\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dselect.exp"
