set test "Completion via comp_load() should be installed"
set cmd "complete -p fold"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load fold\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/fold.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p fold"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt fold\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/fold.exp"
