set test "Completion via comp_load() should be installed"
set cmd "complete -p gprof"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gprof\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gprof.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p gprof"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt gprof\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gprof.exp"
