set test "Completion via comp_load() should be installed"
set cmd "complete -p ifdown"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load ifdown\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ifdown.exp"


set test "Completion via _ifupdown() should be installed"
set cmd "complete -p ifdown"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _ifupdown ifdown\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ifdown.exp"
