set test "Completion via comp_load() should be installed"
set cmd "complete -p mc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mc.exp"


set test "Completion via _mc() should be installed"
set cmd "complete -p mc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _mc mc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mc.exp"
