set test "Completion via comp_load() should be installed"
set cmd "complete -p rcs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load rcs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rcs.exp"


set test "Completion via _rcs() should be installed"
set cmd "complete -p rcs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _rcs rcs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rcs.exp"
