set test "Completion via comp_load() should be installed"
set cmd "complete -p tcpnice"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load tcpnice\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tcpnice.exp"


set test "Completion via _tcpnice() should be installed"
set cmd "complete -p tcpnice"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _tcpnice tcpnice\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tcpnice.exp"
