set test "Completion via comp_load() should be installed"
set cmd "complete -p vgsplit"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load vgsplit\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgsplit.exp"


set test "Completion via _vgsplit() should be installed"
set cmd "complete -p vgsplit"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _vgsplit vgsplit\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgsplit.exp"
