set test "Completion via comp_load() should be installed"
set cmd "complete -p apt-cache"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load apt-cache\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/apt-cache.exp"


set test "Completion via _apt_cache() should be installed"
set cmd "complete -p apt-cache"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _apt_cache apt-cache\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/apt-cache.exp"
