set test "Completion via comp_load() should be installed"
set cmd "complete -p lvscan"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load lvscan\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvscan.exp"


set test "Completion via _lvscan() should be installed"
set cmd "complete -p lvscan"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _lvscan lvscan\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvscan.exp"
