set test "Completion via comp_load() should be installed"
set cmd "complete -p newlist"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load newlist\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/newlist.exp"


set test "Completion via _newlist() should be installed"
set cmd "complete -p newlist"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _newlist newlist\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/newlist.exp"
