set test "Completion via comp_load() should be installed"
set cmd "complete -p ntpdate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load ntpdate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ntpdate.exp"


set test "Completion via _ntpdate() should be installed"
set cmd "complete -p ntpdate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _ntpdate ntpdate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ntpdate.exp"
