set test "Completion via comp_load() should be installed"
set cmd "complete -p portupgrade"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o dirnames -F comp_load portupgrade\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/portupgrade.exp"


set test "Completion via _portupgrade() should be installed"
set cmd "complete -p portupgrade"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o dirnames -F _portupgrade portupgrade\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/portupgrade.exp"
