set test "Completion via comp_load() should be installed"
set cmd "complete -p psql"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load psql\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/psql.exp"


set test "Completion via _psql() should be installed"
set cmd "complete -p psql"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _psql psql\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/psql.exp"
