set test "Completion via comp_load() should be installed"
set cmd "complete -p seq"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load seq\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/seq.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p seq"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _longopt seq\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/seq.exp"
