set test "Completion via comp_load() should be installed"
set cmd "complete -p smartctl"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load smartctl\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/smartctl.exp"


set test "Completion via _smartctl() should be installed"
set cmd "complete -p smartctl"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _smartctl smartctl\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/smartctl.exp"
