set test "Completion via comp_load() should be installed"
set cmd "complete -p svnadmin"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load svnadmin\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svnadmin.exp"


set test "Completion via _svnadmin() should be installed"
set cmd "complete -p svnadmin"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _svnadmin svnadmin\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/svnadmin.exp"
