set test "Completion via comp_load() should be installed"
set cmd "complete -p tar"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o (dirnames|filenames) -F comp_load tar\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tar.exp"


set test "Completion via _tar() should be installed"
set cmd "complete -p tar"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o (dirnames|filenames )-F _tar tar\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tar.exp"
