set test "Completion via comp_load() should be installed"
set cmd "complete -p tee"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load tee\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tee.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p tee"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt tee\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tee.exp"
