set test "Completion via comp_load() should be installed"
set cmd "complete -p tr"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load tr\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tr.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p tr"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt tr\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tr.exp"
