proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "dpkg --c"
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*/@$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


sync_after_int


set test "-L should complete with installed packages"
    # Build list of installed packages
    # NOTE: If an argument is passed to `--get-selections', `dpkg' also returns
    #       packages with status "purged".  Be sure to add `| grep install$' to
    #       pipeline before 'cut' in that case. -- FVu, Sun Feb 22 10:08:34 CET 2009
if {[test_command {dpkg --get-selections | cut -f1 | sort} $test packages]} {
	# Try completion
    set cmd "dpkg -L "
    send "$cmd\t"
    expect_completions $packages $test $cmd
}; # if


sync_after_int


teardown
