proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "svn "
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect

# Interrupt command by sending ^C

send \003;  # Control-c
send "\n"
expect -ex "/@\r\n/@"


set test "Completing --editor-cmd should invoke _command"
    # Try completion
set cmd "svn commit --editor-cmd vim"
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re "^$cmd\r\n.*$cmd$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect

# Interrupt command by sending ^C

send \003;  # Control-c
send "\n"
expect -ex "/@\r\n/@"


teardown
