set test "Completion via comp_load() should be installed"
set cmd "complete -p civclient"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load civclient\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/civclient.exp"


set test "Completion via _civclient() should be installed"
set cmd "complete -p civclient"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _civclient civclient\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/civclient.exp"
