set test "Completion via comp_load() should be installed"
set cmd "complete -p display"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load display\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/display.exp"


set test "Completion via _display() should be installed"
set cmd "complete -p display"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _display display\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/display.exp"
