set test "Completion via comp_load() should be installed"
set cmd "complete -p iwlist"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load iwlist\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/iwlist.exp"


set test "Completion via _iwlist() should be installed"
set cmd "complete -p iwlist"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _iwlist iwlist\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/iwlist.exp"
