set test "Completion via comp_load() should be installed"
set cmd "complete -p ldd"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load ldd\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ldd.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p ldd"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt ldd\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/ldd.exp"
