set test "Completion via comp_load() should be installed"
set cmd "complete -p list_members"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load list_members\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/list_members.exp"


set test "Completion via _list_members() should be installed"
set cmd "complete -p list_members"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _list_members list_members\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/list_members.exp"
