set test "Completion via comp_load() should be installed"
set cmd "complete -p list_admins"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load list_admins\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/list_admins.exp"


set test "Completion via _list_admins() should be installed"
set cmd "complete -p list_admins"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _list_admins list_admins\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/list_admins.exp"
