set test "Completion via comp_load() should be installed"
set cmd "complete -p m4"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load m4\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/m4.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p m4"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt m4\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/m4.exp"
