set test "Completion via comp_load() should be installed"
set cmd "complete -p mailsnarf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load mailsnarf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mailsnarf.exp"


set test "Completion via _snarf() should be installed"
set cmd "complete -p mailsnarf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _snarf mailsnarf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mailsnarf.exp"
