set test "Completion via comp_load() should be installed"
set cmd "complete -p mkfifo"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mkfifo\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mkfifo.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p mkfifo"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt mkfifo\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mkfifo.exp"
