set test "Completion via comp_load() should be installed"
set cmd "complete -p perldoc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load perldoc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/perldoc.exp"


set test "Completion via _perldoc() should be installed"
set cmd "complete -p perldoc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _perldoc perldoc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/perldoc.exp"
