set test "Completion via comp_load() should be installed"
set cmd "complete -p reportbug"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load reportbug\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/reportbug.exp"


set test "Completion via _reportbug() should be installed"
set cmd "complete -p reportbug"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _reportbug reportbug\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/reportbug.exp"
