set test "Completion via comp_load() should be installed"
set cmd "complete -p tcpkill"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load tcpkill\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tcpkill.exp"


set test "Completion via _tcpkill() should be installed"
set cmd "complete -p tcpkill"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _tcpkill tcpkill\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/tcpkill.exp"
