set test "Completion via comp_load() should be installed"
set cmd "complete -p units"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load units\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/units.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p units"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _longopt units\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/units.exp"
