set test "Completion via comp_load() should be installed"
set cmd "complete -p xpovray"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load xpovray\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/xpovray.exp"


set test "Completion via _povray() should be installed"
set cmd "complete -p xpovray"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _povray xpovray\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/xpovray.exp"
