proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "list_owners "
send "$cmd\t"
expect {
    -re "^list_owners .*$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


# Interrupt command by sending ^C

sleep 0.3; 
send \003;  # Control-c
expect -ex /@


teardown
