proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "reportbug -B"
send "$cmd\t"
expect {
    -re "^reportbug .*$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect

# Interrupt command by sending ^C

sleep 0.3; 
send \003;  # Control-c
expect -ex /@


set test "Completing --editor should invoke _command"
    # Try completion
set cmd "reportbug --editor vim"
send "$cmd\t"
expect {
    -re "^$cmd\r\n.*$" { pass "$test" }
    -re "^${cmd}bash: _command: command not found" { fail "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect

# Interrupt command by sending ^C

sleep 0.3; 
send \003;  # Control-c
expect -ex /@


teardown
