proc setup {} {
    set test setup
    set cmd "cd fixtures/scp"
    send "$cmd\r"
    expect -re "^$cmd\r\n/fixtures/scp/@"
}; # setup()


proc teardown {} {
    set test teardown
    set cmd "cd ../.."
    send "$cmd\r"
    expect -re "^$cmd\r\n/@"
}; # teardown()


setup


set test "Tab should complete remote pwd"

    # Retrieving `host_pwd' from ssh-host `bash_completion_lib' yields error? 
    # NOTE: The host should be set in e.g. .ssh/config or /etc/ssh_config
if { 
    [catch {
	exec -- ssh -o "Batchmode yes" bash_completion_lib pwd 2>> /dev/null
    } host_pwd] 
} {
    # Yes, retrieving pwd from ssh yields error; reset `host_pwd'
    set host_pwd ""
}

    # Try completion
set cmd "scp bash_completion_lib:"
send "$cmd\t"
sync_after_tab
expect {
    -re "^$cmd$host_pwd.*$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
}; # expect


sleep .5
sync_after_int


set test "Tab should complete scp known-hosts"
    # Try completion
set cmd "scp -F config "
send "$cmd\t"
set expected "^${cmd}\r\nconfig +doo: +gee: +hus: +known_hosts +\r\n/fixtures/scp/@$cmd$"
expect {
    -re $expected  { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    default { unresolved "$test" }
}; # expect


sync_after_int


teardown
