set test "Completion via comp_load() should be installed"
set cmd "complete -p change_pw"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load change_pw\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/change_pw.exp"


set test "Completion via _change_pw() should be installed"
set cmd "complete -p change_pw"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _change_pw change_pw\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/change_pw.exp"
