set test "Completion via comp_load() should be installed"
set cmd "complete -p convert"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load convert\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/convert.exp"


set test "Completion via _convert() should be installed"
set cmd "complete -p convert"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _convert convert\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/convert.exp"
