set test "Completion via comp_load() should be installed"
set cmd "complete -p dict"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load dict\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dict.exp"


set test "Completion via _dict() should be installed"
set cmd "complete -p dict"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _dict dict\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dict.exp"
