set test "Completion via comp_load() should be installed"
set cmd "complete -p gperf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load gperf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gperf.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p gperf"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt gperf\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/gperf.exp"
