set test "Completion via comp_load() should be installed"
set cmd "complete -p mcrypt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mcrypt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mcrypt.exp"


set test "Completion via _mcrypt() should be installed"
set cmd "complete -p mcrypt"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _mcrypt mcrypt\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mcrypt.exp"
