set test "Completion via comp_load() should be installed"
set cmd "complete -p mkisofs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load mkisofs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mkisofs.exp"


set test "Completion via _mkisofs() should be installed"
set cmd "complete -p mkisofs"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _mkisofs mkisofs\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/mkisofs.exp"
