set test "Completion via comp_load() should be installed"
set cmd "complete -p pr"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load pr\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pr.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p pr"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt pr\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pr.exp"
