set test "Completion via comp_load() should be installed"
set cmd "complete -p screen"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F comp_load screen\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/screen.exp"


set test "Completion via _screen() should be installed"
set cmd "complete -p screen"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o default -F _screen screen\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/screen.exp"
