set test "Completion via comp_load() should be installed"
set cmd "complete -p vgimport"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load vgimport\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgimport.exp"


set test "Completion via _vgmport() should be installed"
set cmd "complete -p vgimport"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _vgport vgimport\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/vgimport.exp"
