proc setup {} {
}; # setup()


proc teardown {} {
}; # teardown()


setup


set test "Tab should complete"
    # Try completion
set cmd "tar "
send "$cmd\t"
expect {
    -re "^$cmd\r\nA +c +d +r +t +u +x +\r\n$" { pass "$test" }
    -re /@ { unresolved "$test at prompt" }
    -re eof { unresolved "eof" }
}; # expect


# Interrupt command by sending ^C

sleep 0.1; 
send \003;  # Control-c
expect -ex /@


teardown
