set test "Completion via comp_load() should be installed"
set cmd "complete -p bc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load bc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/bc.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p bc"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt bc\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/bc.exp"
