set test "Completion via comp_load() should be installed"
set cmd "complete -p dpkg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load dpkg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dpkg.exp"


set test "Completion via _dpkg() should be installed"
set cmd "complete -p dpkg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _dpkg dpkg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/dpkg.exp"
