set test "Completion via comp_load() should be installed"
set cmd "complete -p javac"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load javac\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/javac.exp"


set test "Completion via _javac() should be installed"
set cmd "complete -p javac"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _javac javac\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/javac.exp"
