set test "Completion via comp_load() should be installed"
set cmd "complete -p lvcreate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load lvcreate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvcreate.exp"


set test "Completion via _lvcreate() should be installed"
set cmd "complete -p lvcreate"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _lvcreate lvcreate\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvcreate.exp"
