set test "Completion via comp_load() should be installed"
set cmd "complete -p lvm"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load lvm\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvm.exp"


set test "Completion via _lvm() should be installed"
set cmd "complete -p lvm"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _lvm lvm\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/lvm.exp"
