set test "Completion via comp_load() should be installed"
set cmd "complete -p pvremove"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load pvremove\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvremove.exp"


set test "Completion via _pvremove() should be installed"
set cmd "complete -p pvremove"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F _pvremove pvremove\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/pvremove.exp"
