set test "Completion via comp_load() should be installed"
set cmd "complete -p removepkg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load removepkg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/removepkg.exp"


set test "Completion via _removepkg() should be installed"
set cmd "complete -p removepkg"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _removepkg removepkg\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/removepkg.exp"
