set test "Completion via comp_load() should be installed"
set cmd "complete -p rm"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F comp_load rm\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rm.exp"


set test "Completion via _longopt() should be installed"
set cmd "complete -p rm"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -o filenames -F _longopt rm\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/rm.exp"
