set test "Completion via comp_load() should be installed"
set cmd "complete -p set"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -F comp_load set\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/set.exp"


set test "Completion via -A setopt should be installed"
set cmd "complete -p set"
send "$cmd\r"
expect {
    -re "^$cmd\r\ncomplete -A setopt set\r\n/@$" { pass "$test" }
    -re /@ { fail "$test at prompt" }
}; # expect


source "lib/completions/set.exp"
